### ISSUE TITLE
Use requester-pays buckets?

### ISSUE THREAD

**Issue by willirath** [geomar-od/ESM-VFC-cloud-project#23]
I'd like to use a requester-pays bucket as in https://github.com/willirath/pangeo_ccmp/blob/master/02_example-CCMP-selection.ipynb which is essentially
```python
import intake

cat_pangeo = intake.open_catalog("https://raw.githubusercontent.com/pangeo-data/pangeo-datastore/master/intake-catalogs/master.yaml")

ds_ccmp = cat_pangeo.atmosphere.nasa_ccmp_wind_vectors.to_dask()
display(ds_ccmp)
```
Here, this fails with 
```python-traceback
OSError: Forbidden: https://storage.googleapis.com/download/storage/v1/b/pangeo-nasa-ccmp/o/zarr%2F.zmetadata?alt=media
XXXXXXXXXXXXXXXXXXX does not have serviceusage.services.use access to the Google Cloud project.
```

**Comment by willirath** [comment]
Workflow for enabling use of requester-pays buckets is here: https://github.com/pangeo-data/pangeo-datastore#accessing-requester-pays-data

**Comment by kathoef** [comment]
I have now added a service account that "solves" this automatically. To be used carefully. 😉

**Comment by willirath** [comment]
Looks good. Closing.
